### ISSUE TITLE
App crashes when displaying profile image on the Profile Screen

### ISSUE THREAD

**Issue by khwilo** [khwilo/GitHubFollowers#9]
Serving images from the network causes the application to crash.

## Steps to reproduce the error

1. Search for followers
2. Click on a particular follower avatar

I'm using a combination of useState and Context API to find a user from a list of GitHub followers.

## Possible solution

- Perform another network call to fetch the user profile data
- Use [React Native Fast Image](https://github.com/DylanVann/react-native-fast-image)

## References

- <https://github.com/facebook/react-native/issues/12220>
- <https://github.com/facebook/react-native/issues/21982>

**Comment by khwilo** [comment]
The app currently uses an image placeholder view instead of the Image component because of this bug. The image placeholder view has a background color of green.

![user-profile-screen-phone](https://user-images.githubusercontent.com/5740429/97451739-1626a000-1945-11eb-975a-65666c6e3179.png)

**Comment by benzerbett** [comment]
Share the error log as well. I'm curious

**Comment by khwilo** [comment]
@benzerbett the app crashes without any error. I think it is a similar issue to this: <https://github.com/facebook/react-native/issues/21982>. However, I've not yet profiled the application to see the exact step that it crashes. I'm still looking into it.

**Comment by khwilo** [comment]
# Solution

I found a solution to this bug. I implemented a global store using Redux to hold the application state, then used the image URL value from the store to update the image in the Profile Screen.

The profile image URL  is referenced as `user.avatar_url`. The value of `user.avatar_url` is cast as a string before displaying it. Remember to provide a width and height value for the image for it to display on the screen.

```javascript
<Image
    source={{ uri: `${user.avatar_url}` }}
    style={{ width: 120, height: 120 }}
/>
```

## Possible causes of the bug

1. Using application states not shared with other components may have caused unnecessary components remounts that eventually led to the application crashing.
2. Poor useEffect hook implementation also may have caused unnecessary components remounts coupled with multiple UI renders.
